# permissions for end users to view repurikas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: repurika-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: repurika
    app.kubernetes.io/part-of: repurika
    app.kubernetes.io/managed-by: kustomize
  name: repurika-viewer-role
rules:
- apiGroups:
  - batch.bonavadeur.io
  resources:
  - repurikas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.bonavadeur.io
  resources:
  - repurikas/status
  verbs:
  - get
